# Generated by Django 2.2 on 2021-07-17 07:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='plot_no',
            field=models.BigIntegerField(null=True),
            preserve_default=False,
        ),
    ]
