# Generated by Django 2.2 on 2021-07-17 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_plot_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='plot_no',
            field=models.BigIntegerField(null=True),
        ),
    ]
