# Generated by Django 2.2 on 2021-04-22 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shapefiles', '0004_auto_20210422_1155'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Parcel',
            new_name='Old',
        ),
        migrations.AlterModelOptions(
            name='old',
            options={'verbose_name_plural': 'Old'},
        ),
    ]
