# Generated by Django 2.2 on 2021-04-22 07:42

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shapefiles', '0005_auto_20210422_1324'),
    ]

    operations = [
        migrations.CreateModel(
            name='OldParcel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=50)),
                ('finalparce', models.BigIntegerField()),
                ('existing_a', models.FloatField()),
                ('ropani_aan', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
            options={
                'verbose_name_plural': 'Old',
            },
        ),
        migrations.DeleteModel(
            name='Old',
        ),
    ]
