# Generated by Django 2.2 on 2021-04-22 15:06

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shapefiles', '0006_auto_20210422_1327'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('owner_name', models.CharField(max_length=50)),
                ('finalparce', models.FloatField()),
                ('existing_a', models.FloatField()),
                ('ropani_aan', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
            options={
                'verbose_name_plural': 'Parcel',
            },
        ),
    ]
