# Generated by Django 2.2 on 2021-04-22 15:23

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shapefiles', '0007_parcel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326),
        ),
    ]
