# Generated by Django 2.2 on 2021-04-22 15:44

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shapefiles', '0009_auto_20210422_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='final',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(srid=32644),
        ),
        migrations.AlterField(
            model_name='oldparcel',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(srid=32644),
        ),
    ]
