# Generated by Django 2.2 on 2021-04-24 15:04

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shapefiles', '0011_plot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parcel',
            name='finalparce',
        ),
        migrations.AddField(
            model_name='parcel',
            name='aana',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parcel',
            name='paisa',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parcel',
            name='parcelno',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parcel',
            name='ropani',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='existing_a',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='owner_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='ropani_aan',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
