# Generated by Django 2.2 on 2021-04-24 15:09

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shapefiles', '0012_auto_20210424_2049'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parcel1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(blank=True, max_length=50, null=True)),
                ('parcelno', models.FloatField(blank=True, null=True)),
                ('existing_a', models.FloatField(blank=True, null=True)),
                ('ropani_aan', models.FloatField(blank=True, null=True)),
                ('ropani', models.FloatField(blank=True, null=True)),
                ('aana', models.FloatField(blank=True, null=True)),
                ('paisa', models.FloatField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
            ],
            options={
                'verbose_name_plural': 'Parcel',
            },
        ),
        migrations.DeleteModel(
            name='Parcel',
        ),
    ]
