# Generated by Django 2.2 on 2021-04-24 15:27

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shapefiles', '0013_auto_20210424_2054'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plot1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shape_leng', models.FloatField()),
                ('shape_area', models.FloatField()),
                ('plot_no', models.BigIntegerField()),
                ('ropani', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
            options={
                'verbose_name_plural': 'Plot1',
            },
        ),
        migrations.AlterModelOptions(
            name='parcel1',
            options={'verbose_name_plural': 'Parcel1'},
        ),
    ]
