# Generated by Django 2.2 on 2021-04-25 08:46

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shapefiles', '0015_poi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=50)),
                ('parcelno', models.BigIntegerField()),
                ('existing_a', models.FloatField()),
                ('ropani_aan', models.FloatField()),
                ('category', models.CharField(max_length=7)),
                ('ropani', models.BigIntegerField()),
                ('aana', models.BigIntegerField()),
                ('paisa', models.BigIntegerField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
            options={
                'verbose_name_plural': 'Parcel',
            },
        ),
    ]
