# Generated by Django 2.2 on 2021-04-25 08:55

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shapefiles', '0016_parcel'),
    ]

    operations = [
        migrations.CreateModel(
            name='poi1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point_id', models.BigIntegerField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPointField(srid=4326)),
            ],
            options={
                'verbose_name_plural': 'Poi',
            },
        ),
    ]
