# Generated by Django 2.2 on 2021-04-26 02:11

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shapefiles', '0017_poi1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Joint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plot_no', models.BigIntegerField()),
                ('plot_perim', models.FloatField()),
                ('plot_area', models.FloatField()),
                ('ropani', models.FloatField()),
                ('owner_name', models.CharField(max_length=50)),
                ('existing_a', models.FloatField()),
                ('owner_ropa', models.FloatField()),
                ('owner_key', models.BigIntegerField()),
                ('category', models.CharField(max_length=7)),
                ('distri_are', models.FloatField()),
                ('par_whole', models.CharField(max_length=1)),
                ('distri_pa', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
            options={
                'verbose_name_plural': 'Joint',
            },
        ),
    ]
